#!/usr/bin/env python3
"""
Weekly Cash Forecast Email

Generates a week-ahead projection and sends via email.
Scheduled for Sunday mornings.
"""

import json
import subprocess
import sys
from datetime import datetime, timedelta
from pathlib import Path

THANOS_ROOT = Path(__file__).parent.parent


def get_forecast_data() -> dict:
    """Run financial forecasting and get analysis."""
    cmd = [sys.executable, str(THANOS_ROOT / "Tools" / "financial_forecasting.py")]
    
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120, cwd=THANOS_ROOT)
        
        # Parse JSON from stderr
        stderr = result.stderr
        json_start = stderr.find('{')
        if json_start >= 0:
            return json.loads(stderr[json_start:])
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
    
    return {}


def generate_email_body(data: dict) -> str:
    """Generate formatted email body."""
    now = datetime.now()
    week_end = now + timedelta(days=7)
    
    velocity = data.get("velocity", {})
    runway = data.get("runway", {})
    scenarios = data.get("scenarios", {})
    income = data.get("income", {})
    warnings = data.get("warnings", [])
    
    daily_burn = velocity.get("daily_burn", 0)
    liquid = runway.get("liquid_cash", 0)
    
    # Project 7 days out
    week_spend = daily_burn * 7
    week_end_balance = liquid - week_spend
    
    body = f"""
Weekly Cash Flow Forecast
{now.strftime('%B %d, %Y')} - {week_end.strftime('%B %d, %Y')}
{'=' * 50}

CURRENT POSITION
  Cash Available: ${liquid:,.2f}
  Daily Burn Rate: ${daily_burn:,.2f}/day
  Cash Runway: {runway.get('days', 0):.0f} days

7-DAY PROJECTION
  Expected Spending: ${week_spend:,.2f}
  Projected Balance: ${week_end_balance:,.2f}

END OF MONTH SCENARIOS
"""
    
    for name, scenario in scenarios.items():
        emoji = "🟢" if name == "best_case" else "🟡" if name == "expected" else "🔴"
        body += f"  {emoji} {scenario['description']}: ${scenario['eom_balance']:,.2f}\n"
    
    body += f"""
INCOME STATUS
  MTD Income: ${income.get('mtd_income', 0):,.2f}
  Expected: ${income.get('expected_to_date', 0):,.2f}
  Status: {income.get('status', 'unknown').upper()}
"""
    
    if warnings:
        body += "\nALERTS\n"
        for w in warnings[:5]:
            body += f"  • {w}\n"
    
    body += f"""
{'=' * 50}
Generated by Thanos Financial System
"""
    
    return body.strip()


def main():
    """Generate and output weekly forecast."""
    data = get_forecast_data()
    
    if not data:
        print("Could not generate forecast data")
        sys.exit(1)
    
    email_body = generate_email_body(data)
    print(email_body)
    
    # Output subject line
    velocity = data.get("velocity", {})
    runway = data.get("runway", {})
    print(f"\n---SUBJECT---")
    print(f"Weekly Cash Forecast: ${runway.get('liquid_cash', 0):,.0f} | {runway.get('days', 0):.0f} days runway")


if __name__ == "__main__":
    main()
